"use strict";
const {loadProviders,providerForApplication}=require("../provider-manager");
const agentCtrl=require("./backends/agent-ctrl");
function normalizeRef(raw){let primitive="";if(typeof raw==="string")primitive=raw;else if(Array.isArray(raw))primitive=raw[0]??"";else if(raw&&typeof raw==="object")primitive=raw.value??raw.id??raw.ref??raw[0]??"";const value=String(primitive||"");let m=value.match(/^@([es])(\d+)$/);if(m)return`@${m[1]}${m[2]}`;m=value.match(/^ref_(\d+)$/);if(m)return`@e${m[1]}`;m=value.match(/^scope_(\d+)$/);if(m)return`@s${m[1]}`;return null;}
function normalizeRole(raw){return String(raw||"").normalize("NFKC").toLowerCase().replace(/[\s_]+/g,"-").trim();}
function snapshotRoot(data){if(data?.root)return data;if(data?.snapshot?.root)return data.snapshot;if(data?.result?.root)return data.result;if(data?.data?.root)return data.data;return null;}
function snapshotTree({app,settle=false,depth=12}){const provider=providerForApplication(app,loadProviders());if(!provider)return{ok:false,error:"PROVIDER_NOT_FOUND",detail:`No application Provider registered for "${app}"`};const observed=agentCtrl.snapshotApplicationJson(provider,provider.identity||null,Boolean(settle),{compact:false,depth});if(!observed.ok)return{ok:false,error:"SNAPSHOT_FAILED",detail:(observed.stderr||"native AX JSON snapshot failed").trim(),method:observed.method,observeSeconds:observed.seconds||0};const snapshot=snapshotRoot(observed.data);if(!snapshot)return{ok:false,error:"SNAPSHOT_DECODE_FAILED",detail:"agent-ctrl JSON snapshot does not contain a root node",method:observed.method,observeSeconds:observed.seconds||0};return{ok:true,snapshot,root:snapshot.root,method:observed.method,observeSeconds:observed.seconds||0};}
function findNode(root,target){const wanted=normalizeRef(target?.ref);const descriptorRole=normalizeRole(target?.role);const descriptorName=String(target?.name||"");let exact=null;const descriptor=[];function visit(node,path){if(!node||typeof node!=="object")return;const ref=normalizeRef(node.ref_id??node.refId??node.ref);const role=normalizeRole(node.role);const name=String(node.name||"");const current={node,ref,role,name,path};if(ref&&ref===wanted)exact=current;if(descriptorRole&&descriptorName&&role===descriptorRole&&name===descriptorName)descriptor.push(current);for(const child of Array.isArray(node.children)?node.children:[])visit(child,[...path,node]);}visit(root,[]);if(exact)return{ok:true,...exact,rebound:false};if(descriptor.length===1)return{ok:true,...descriptor[0],rebound:true};if(descriptor.length>1)return{ok:false,error:"CONTROL_TARGET_AMBIGUOUS",detail:`${descriptor.length} native AX nodes match ${descriptorRole} ${JSON.stringify(descriptorName)}`};return{ok:false,error:"CONTROL_TARGET_STALE",detail:`Target ${wanted||target?.ref||""} is not present in the fresh native AX tree`};}
function nodeState(node){return node&&typeof node.state==="object"&&!Array.isArray(node.state)?node.state:{};}
function collectDescendants(found,{depth=1,role=null}){const out=[];const wantedRole=normalizeRole(role);function visit(node,relativeDepth){if(relativeDepth>depth)return;for(const child of Array.isArray(node.children)?node.children:[]){const d=relativeDepth;const ref=normalizeRef(child.ref_id??child.refId??child.ref);const childRole=normalizeRole(child.role);const state=nodeState(child);if(ref&&(!wantedRole||childRole===wantedRole))out.push({ref,role:childRole||"unknown",name:String(child.name||""),disabled:state.enabled===false,depth:d});if(d<depth)visit(child,d+1);}}visit(found.node,1);return out;}
function rectangle(node){const b=node?.bounds;if(!b)return null;const x=Number(b.x??b.origin?.x),y=Number(b.y??b.origin?.y),width=Number(b.width??b.w??b.size?.width),height=Number(b.height??b.h??b.size?.height);return[x,y,width,height].every(Number.isFinite)&&width>=0&&height>=0?{x,y,width,height}:null;}
function nearestAncestor(found,role){const wanted=normalizeRole(role);for(let i=found.path.length-1;i>=0;i--){const node=found.path[i];if(normalizeRole(node.role)===wanted)return node;}return null;}
function nearestScrollAncestor(found){for(let i=found.path.length-1;i>=0;i--){const node=found.path[i];const role=normalizeRole(node.role);if(role==="scroll-area"||role==="scroll-view")return node;if(role==="group"&&(Array.isArray(node.children)?node.children:[]).some(child=>normalizeRole(child.role)==="slider"))return node;}return null;}
function intersects(a,b){if(!a||!b)return false;return a.x+a.width>b.x&&b.x+b.width>a.x&&a.y+a.height>b.y&&b.y+b.height>a.y;}
function stableNodeSignature(node){if(!node)return null;const clean=n=>({role:normalizeRole(n.role),name:String(n.name||""),value:n.value??null,state:n.state??null,bounds:rectangle(n),children:(Array.isArray(n.children)?n.children:[]).map(clean)});return JSON.stringify(clean(node));}
module.exports={normalizeRef,normalizeRole,snapshotTree,findNode,collectDescendants,rectangle,nearestAncestor,nearestScrollAncestor,intersects,stableNodeSignature};
