export * from "./index-stateful";
import type {ControlDescription as BaseControlDescription,InvokeResult as BaseInvokeResult,ToggleResult as BaseToggleResult,SelectResult as BaseSelectResult,ObservedTarget,VerifiedOperationResult} from "./index-stateful";
export interface ControlDescription extends BaseControlDescription {}
export interface InvokeResult extends BaseInvokeResult {}
export interface ToggleResult extends BaseToggleResult {}
export interface SelectResult extends BaseSelectResult {}
export interface ApplicationDescriptor {name:string;providerId:string;available:boolean;running:boolean;active:boolean;bundle:string|null;}
export interface ApplicationListResult {state:"OBSERVED";applications:ApplicationDescriptor[];observation:{method:string};backend:{name:string;strategy:string};}
export interface ApplicationLifecycleResult extends VerifiedOperationResult {state:"APPLICATION_RUNNING"|"APPLICATION_ACTIVE"|"APPLICATION_TERMINATED";application:ApplicationDescriptor;changed:boolean;idempotent:boolean;}
export interface DialogButtonObservation {label:string|null;enabled:boolean|null;}
export interface DialogObservation {kind:"dialog"|"sheet";title:string|null;texts:string[];modal:boolean|null;buttons:DialogButtonObservation[];}
export interface DialogListResult {state:"OBSERVED";application:ApplicationDescriptor;dialogs:DialogObservation[];observation:{method:string};backend:{name:string;strategy:string};diagnostics?:Record<string,unknown>;}
export interface DialogActionResult extends VerifiedOperationResult {state:"DIALOG_ACTION_COMPLETED";action:"default"|"cancel";application:ApplicationDescriptor;changed:true;idempotent:false;}
export interface MenuBarItemObservation {title:string;enabled:boolean|null;children:MenuBarItemObservation[];}
export interface MenuBarObservation {items:MenuBarItemObservation[];}
export interface MenuBarObserveResult {state:"OBSERVED";application:ApplicationDescriptor;menuBar:MenuBarObservation|null;observation:{method:string};backend:{name:string;strategy:string};diagnostics?:Record<string,unknown>;}
export interface DockItemObservation {kind:"application"|"folder"|"trash"|"separator"|"other";title:string|null;running:boolean|null;status:string|null;}
export interface DockObservation {items:DockItemObservation[];}
export interface DockObserveResult {state:"OBSERVED";dock:DockObservation|null;observation:{method:string};backend:{name:string;strategy:string};diagnostics?:Record<string,unknown>;}
export interface MenuExtraItemObservation {title:string|null;description:string|null;value:string|null;enabled:boolean|null;}
export interface MenuExtrasObservation {items:MenuExtraItemObservation[];}
export interface MenuExtrasObserveResult {state:"OBSERVED";menuExtras:MenuExtrasObservation|null;observation:{method:string};backend:{name:string;strategy:string};diagnostics?:Record<string,unknown>;}
export interface FilePickerItemObservation {name:string;kind:"file"|"directory"|"unknown";selected:boolean|null;enabled:boolean|null;}
export interface FilePickerObservation {kind:"open";location:string|null;items:FilePickerItemObservation[];}
export interface FilePickerObserveResult {state:"OBSERVED";application:ApplicationDescriptor;picker:FilePickerObservation|null;observation:{method:string};backend:{name:string;strategy:string};diagnostics?:Record<string,unknown>;}
export interface FilePickerItemSelectionResult extends VerifiedOperationResult {state:"FILE_PICKER_ITEM_SELECTED";application:ApplicationDescriptor;item:FilePickerItemObservation;location:string|null;changed:boolean;idempotent:boolean;}
export interface FilePickerDirectoryExpansionResult extends VerifiedOperationResult {state:"FILE_PICKER_DIRECTORY_EXPANDED";application:ApplicationDescriptor;directory:{name:string;kind:"directory"};location:string|null;picker?:FilePickerObservation;changed:boolean;idempotent:boolean;}
export interface FilePickerSemanticActionResult extends VerifiedOperationResult {state:"FILE_PICKER_ACCEPTED"|"FILE_PICKER_CANCELLED";action:"accept"|"cancel";application:ApplicationDescriptor;changed:true;idempotent:false;}
export interface DisclosureResult extends VerifiedOperationResult {state:"EXPANDED"|"COLLAPSED";target:ObservedTarget;previousValue:boolean;observedValue:boolean;changed:boolean;idempotent:boolean;}
export interface ValueMutationResult extends VerifiedOperationResult {state:"VALUE_SET"|"INCREMENTED"|"DECREMENTED";target:ObservedTarget;previousValue:string|number;observedValue:string|number;changed:boolean;idempotent:boolean;requestedValue?:string|number;}
export interface StructuralTarget {ref:string;role?:string;name?:string;}
export interface StructuralChild extends StructuralTarget {role:string;name:string;disabled:boolean;depth:number;}
export interface ChildrenResult {state:"OBSERVED";target:StructuralTarget;children:StructuralChild[];total:number;offset:number;limit:number;hasMore:boolean;depth:number;role:string|null;observation:{method:string;rebound?:boolean};backend:{name:string;strategy:string};}
export interface ScrollResult extends VerifiedOperationResult {state:"SCROLLED";target:ObservedTarget;direction:"up"|"down";amount:number;}
export interface ScrollIntoViewResult extends VerifiedOperationResult {state:"VISIBLE";target:ObservedTarget;idempotent:boolean;changed:boolean;}
export type TextIndexUnit = "utf16-code-unit";
export interface TextRangeRequest {start:number;end:number;unit:TextIndexUnit;}
export interface TextSelectionRange {start:number;end:number;length:number;collapsed:boolean;unit:TextIndexUnit;}
export interface TextSelectionResult {state:"OBSERVED";target:ObservedTarget;selection:TextSelectionRange;caret:number|null;selectedText:string|null;textLength:number|null;observation:{method:string;reboundBy:"role-and-accessible-name";indexUnit:TextIndexUnit};backend:{name:string;strategy:string};diagnostics?:Record<string,unknown>;}
export interface TextRangeSelectionResult extends VerifiedOperationResult {state:"TEXT_RANGE_SELECTED";target:ObservedTarget;requestedRange:TextSelectionRange;previousRange:TextSelectionRange;observedRange:TextSelectionRange;caret:number|null;selectedText:string|null;changed:boolean;idempotent:boolean;}
export interface TextMutationResult extends VerifiedOperationResult {state:"TEXT_MUTATED";operation:"ui.replaceTextRange"|"ui.insertText"|"ui.appendText";target:ObservedTarget;requestedRange:TextSelectionRange;replacementLength:number;previousTextLength:number;resultingTextLength:number;resultingSelection:TextSelectionRange;caret:number;textChanged:boolean;selectionChanged:boolean;changed:boolean;idempotent:boolean;}
declare module "./index-stateful" {interface ComputerControlClient {listApplications(params?:{availableOnly?:boolean}):Promise<ApplicationListResult>;launchApplication(params:{application:string;timeoutMs?:number}):Promise<ApplicationLifecycleResult>;activateApplication(params:{application:string;timeoutMs?:number}):Promise<ApplicationLifecycleResult>;terminateApplication(params:{application:string;timeoutMs?:number}):Promise<ApplicationLifecycleResult>;listDialogs(params:{application:string}):Promise<DialogListResult>;invokeDialogDefault(params:{application:string;timeoutMs?:number}):Promise<DialogActionResult>;invokeDialogCancel(params:{application:string;timeoutMs?:number}):Promise<DialogActionResult>;observeMenuBar(params:{application:string}):Promise<MenuBarObserveResult>;observeDock():Promise<DockObserveResult>;observeMenuExtras():Promise<MenuExtrasObserveResult>;observeFilePicker(params:{application:string}):Promise<FilePickerObserveResult>;selectFilePickerItem(params:{application:string;name:string;timeoutMs?:number}):Promise<FilePickerItemSelectionResult>;expandFilePickerDirectory(params:{application:string;name:string;timeoutMs?:number}):Promise<FilePickerDirectoryExpansionResult>;acceptFilePicker(params:{application:string;timeoutMs?:number}):Promise<FilePickerSemanticActionResult>;cancelFilePicker(params:{application:string;timeoutMs?:number}):Promise<FilePickerSemanticActionResult>;expand(params:{application:string;target:ObservedTarget;settle?:boolean}):Promise<DisclosureResult>;collapse(params:{application:string;target:ObservedTarget;settle?:boolean}):Promise<DisclosureResult>;setValue(params:{application:string;target:ObservedTarget;value:string|number;settle?:boolean}):Promise<ValueMutationResult>;increment(params:{application:string;target:ObservedTarget;settle?:boolean}):Promise<ValueMutationResult>;decrement(params:{application:string;target:ObservedTarget;settle?:boolean}):Promise<ValueMutationResult>;children(params:{application:string;target:StructuralTarget;role?:string|null;depth?:number;offset?:number;limit?:number}):Promise<ChildrenResult>;scroll(params:{application:string;target:ObservedTarget;direction:"up"|"down";amount?:number;settle?:boolean}):Promise<ScrollResult>;scrollIntoView(params:{application:string;target:ObservedTarget}):Promise<ScrollIntoViewResult>;getTextSelection(params:{application:string;target:ObservedTarget}):Promise<TextSelectionResult>;selectTextRange(params:{application:string;target:ObservedTarget;range:TextRangeRequest}):Promise<TextRangeSelectionResult>;replaceTextRange(params:{application:string;target:ObservedTarget;range:TextRangeRequest;text:string}):Promise<TextMutationResult>;insertText(params:{application:string;target:ObservedTarget;text:string}):Promise<TextMutationResult>;appendText(params:{application:string;target:ObservedTarget;text:string}):Promise<TextMutationResult>;}}
